#spring.application.name=apigateway

server:
  port: 8080
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: bookingapi
          uri: lb://bookingapi
          predicates:
            - Path=/booking/**
        - id: flightsapi
          uri: lb://flightsapi
          predicates:
            - Path=/flights/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8787/eureka
